"""Storage initial

Revision ID: 4ca480fd7c8e
Revises: d7abdbdea08f
Create Date: 2024-03-27 15:45:03.599675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca480fd7c8e'
down_revision: Union[str, None] = 'd7abdbdea08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id_place', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_item'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['id_place'], ['places.place_id'], ),
    sa.ForeignKeyConstraint(['item'], ['items.item_name'], ),
    sa.ForeignKeyConstraint(['place'], ['places.place_name'], ),
    sa.ForeignKeyConstraint(['weight'], ['items.item_weight'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage')
    # ### end Alembic commands ###
