"""Database creation

Revision ID: d7abdbdea08f
Revises: 
Create Date: 2024-03-22 10:45:05.631407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7abdbdea08f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('item_name', sa.String(), nullable=False),
                    sa.Column('item_weight', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('places',
                    sa.Column('place_id', sa.Integer(), nullable=False),
                    sa.Column('place_name', sa.String(), nullable=False),
                    sa.Column('max_weight', sa.Float(), nullable=False),
                    sa.Column('remaining_weight', sa.Float()),
                    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_name', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('storage')
    op.drop_table('items')
    # ### end Alembic commands ###
